stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE"

build_and_push:
  stage: build
  image: docker:cli
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker build -t "$IMAGE_NAME:$CI_COMMIT_TAG" -t "$IMAGE_NAME:latest" --push .
      else
        SAFE_BRANCH=$(echo "$CI_COMMIT_REF_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
        docker build -t "$IMAGE_NAME:$SAFE_BRANCH" --push .
      fi
  only:
    - branches
    - tags

deploy-stage:
  stage: deploy
  tags: [ deploy ]
  needs:
    - job: build_and_push
      artifacts: false
  rules:
    - if: '$CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH"'
  before_script:
    - cp "$DEV_ENV_FILE" .env
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker pull "$IMAGE_NAME:$CI_DEFAULT_BRANCH"
    - docker rm -f "$CI_PROJECT_NAME-$CI_DEFAULT_BRANCH" || true
    - |
      docker run -d \
        --name "$CI_PROJECT_NAME-$CI_DEFAULT_BRANCH" \
        --restart always \
        --env-file .env \
        -p 127.0.0.1:5173:80 \
        --network crm-bot  \
        "$IMAGE_NAME:$CI_DEFAULT_BRANCH"